site_name: Fudge
site_url: https://danielc.dev/fudge
site_description: Fudge app
site_author: Daniel Cook

repo_url: https://github.com/petabyt/fudge
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    scheme: slate

nav:
    - Home: index.md
    - Help: help.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
